#Database
POSTGRESQL_USERNAME:maxi
POSTGRESQL_PASSWORD:maxi
POSTGRESQL_HOST:localhost
POSTGRESQL_PORT:5434
POSTGRESQL_DATABASE:docsDB
  
  #Server
CONTAINER_PORT:8085
ACTIVE_PROFILE:prod
  
  #Email Config
EMAIL_HOST:smtp.gmail.com
EMAIL_PORT:587
EMAIL_ID:onyemax247@gmail.com
EMAIL_PASSWORD:wspfjavzhxawgyzw
VERIFY_EMAIL_HOST:http://localhost:8085